name: Protector
version: '${project.version}'
main: com.arctic.Protector

commands:
  protector:
    description: Reload protector config file
    permission: protector.reload
    permission-message: You can not use that command!
